### ISSUE TITLE
Failed to load stylesheet main.css

### ISSUE THREAD

**Issue by 1kastner** [useblocks/sphinx-simplepdf#22]
In the logs, the following statement is shown:

```
ERROR: Failed to load stylesheet at file:///C:/.../docs/_build/simplepdf/_static/styles/main.css: URLError: <urlopen error [WinError 2] Das System kan
n die angegebene Datei nicht finden: 'C:\\...\\docs\\_build\\simplepdf\\_static\\styles\\main.css'>
```

Is that stylesheet optional? I guess simplepdf fails to copy it from somewhere to that target directory?

**Comment by danwos** [comment]
Mhh, no it's not optional.
`main.css` is stored under `_static` directly. 
And must be available, as it contains all our styles. Without it, the PDF would look really ugly.

I don't have such a message in my logs.
Are you working with the latest `main` branch?

**Comment by 1kastner** [comment]
I am working with the main branch. This error message has always shown up, I also remember seeing it in my very first build. Maybe it is the cause why my SVG images are still poorly aligned?

**Comment by danwos** [comment]
That look good to me. `main.css` is in `_static`.
`styles` is not really needed. It's only used to generate `main.css` which should contain everything and is the only CSS file we need.

We generated `main.css` in `styles` some commits ago. But this was changed. 

So I think the problem is, that `styles/main.css` still gets registered somewhere.
